### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by naren8642** [cdukes/bones-for-genesis-2-0#32]
I tried out your build steps and I can see that the css and js files are generated. Would it be possible to enhance the Gruntfile such that build would create a complete theme folder with all the required files?

**Comment by cdukes** [comment]
Yes, you could use [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy) to move other assets into the build folder, or change the Grunt config to drop the CSS/JS somewhere else. 

But I don't know why you'd do that, since the BFG root folder is a complete WP child theme itself, and already set to look in the build folder for assets?
